source_job_name: 'source_get_hotel_bookings'
source_job_id: 3
source_folder_name: 'hotel_bookings'
source_file_name: 'hotel_bookings.csv'
target_table_name: 'hotel_bookings'
target_schema_name: 'sourced'