target_job_name: 'target_get_seoul_bikes'
target_job_id: 5
sourced_schema_name: 'sourced'
sourced_table_name: 'seoul_bikes'
target_table_name: 'seoul_bikes'
target_schema_name: 'cleansed'
remove_nulls: 'Date'